title: Archetype
baseurl: /
landing_template: home
footer:
  about:
    enabled: true
    title: Integer vitae sed feugiat
    text: >-
      Lorem ipsum dolor sit amet interdum mollis sapien. Sed amet ac lorem ipsum
      interdum tempus sagittis lorem tempus.
    actions:
      - label: Learn More
        url: no-sidebar.md
        is_primary: false
        is_scrolly: false
  contact_methods:
    enabled: true
    methods_col1:
      - title: Address
        icon: fa-map-marker
        text: |-
          Untitled Corp  
          1234 Fictional Road  
          Suite 5432  
          Nashville, TN 00000
        type: contact_with_text
        template: contact_with_text
    methods_col2:
      - title: Phone
        icon: fa-phone
        text: (000) 000-0000
        type: contact_with_text
        template: contact_with_text
      - title: Email
        icon: fa-envelope-o
        text: information@untitled.tld
        url: '#'
        type: contact_with_link
        template: contact_with_link
  copyright:
    enabled: true
    text: '&copy; Untitled. All rights reserved.'
palette: blue
palettes:
  blue:
    sass:
      gradient1: '#27a1e3'
      gradient2: '#e7232a'
      accent1: '#5f9dd2'
      accent2: '#758ce1'
      accent3: '#e286a9'
  green:
    sass:
      gradient1: '#16f4cf'
      gradient2: '#6532e5'
      accent1: '#54d3cf'
      accent2: '#4f92d1'
      accent3: '#8075e5'
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
permalink: '/posts/:slug:output_ext'
